# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  matrix:
    - platform: x64
  GH_TOKEN:
    secure: dqaeEhkA+L9BZ0IxHyB5euvuq201mxDelxKcvwlsovvWYZbTReC29RyvZp/wCP91

image: Visual Studio 2017

init:
  - npm config set msvs_version 2017

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn release

shallow_clone: true

test_script:
  - node --version
  - yarn --version

on_success:
  - ps: Get-ChildItem .\dist\*\*.exe | % { Push-AppveyorArtifact $_.FullName }
